/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CombatImport } from './routes/combat'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const CombatRoute = CombatImport.update({
  path: '/combat',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/combat': {
      id: '/combat'
      path: '/combat'
      fullPath: '/combat'
      preLoaderRoute: typeof CombatImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({ IndexRoute, CombatRoute })

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/combat"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/combat": {
      "filePath": "combat.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
