/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WorldImport } from './routes/world'
import { Route as EncounterImport } from './routes/encounter'
import { Route as CombatImport } from './routes/combat'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const WorldRoute = WorldImport.update({
  path: '/world',
  getParentRoute: () => rootRoute,
} as any)

const EncounterRoute = EncounterImport.update({
  path: '/encounter',
  getParentRoute: () => rootRoute,
} as any)

const CombatRoute = CombatImport.update({
  path: '/combat',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/combat': {
      id: '/combat'
      path: '/combat'
      fullPath: '/combat'
      preLoaderRoute: typeof CombatImport
      parentRoute: typeof rootRoute
    }
    '/encounter': {
      id: '/encounter'
      path: '/encounter'
      fullPath: '/encounter'
      preLoaderRoute: typeof EncounterImport
      parentRoute: typeof rootRoute
    }
    '/world': {
      id: '/world'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof WorldImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  CombatRoute,
  EncounterRoute,
  WorldRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/combat",
        "/encounter",
        "/world"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/combat": {
      "filePath": "combat.tsx"
    },
    "/encounter": {
      "filePath": "encounter.tsx"
    },
    "/world": {
      "filePath": "world.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
