import {
  AttackDownAllOtherOnUnitEnterId,
  AttackDownParentId,
  AttackUpParentId,
  CreateSandstormOnUnitEnterId,
  DamageAllOnTurnEndId,
  DamageNewUnitsOnUnitEnterId,
  DamageParentOnTurnEndId,
  DefenseDownParentId,
  DefneseUpParentId,
  DisabledParentId,
  DivineHealingId,
  FireDamageUpParentId,
  FireNegationUpParentId,
  HealParentOnTurnEndId,
  HealParentOnUnitSwitchId,
  HexedParentId,
  InspectAllOnUnitEnterId,
  InspectedAllId,
  InvertSpeedAllId,
  PoisonedDamageOnTurnEndId,
  PowerStanceId,
  ProtectedParentId,
  SandstormOnTurnEndId,
  SpeedUpParentId,
  SpeedUpTeamId,
  StunnedParentId,
} from '@repo/game/data'

export const MODIFIER_NAMES: Record<string, string> = {
  [DamageAllOnTurnEndId]: 'Damage All on Turn End',
  [DamageNewUnitsOnUnitEnterId]: 'Spikes',
  [DamageParentOnTurnEndId]: 'Damage on Turn End',
  [CreateSandstormOnUnitEnterId]: 'Sand Stream',
  [HealParentOnTurnEndId]: 'Heal Parent On Turn End',
  [DivineHealingId]: 'Divine Healing',
  [HealParentOnUnitSwitchId]: 'Regenerate',
  [InspectAllOnUnitEnterId]: 'Scholar',
  [AttackDownAllOtherOnUnitEnterId]: 'Intimidate',
  [SandstormOnTurnEndId]: 'Sandstorm',
  [PoisonedDamageOnTurnEndId]: 'Poisoned',

  [DefenseDownParentId]: 'Defense Down',
  [DefneseUpParentId]: 'Defense Up',
  [DisabledParentId]: 'Disabled',
  [HexedParentId]: 'Hexed',
  [ProtectedParentId]: 'Protected',
  [InspectedAllId]: 'Inspected',
  [FireDamageUpParentId]: 'Fire Damage Up',
  [FireNegationUpParentId]: 'Fire Damage Negation Up',
  [StunnedParentId]: 'Stun',
  [InvertSpeedAllId]: 'Invert Speed',
  [AttackDownParentId]: 'Attack Down',
  [AttackUpParentId]: 'Attack Up',
  [SpeedUpTeamId]: 'Speed Up',
  [SpeedUpParentId]: 'Speed Up',
  [PowerStanceId]: 'Power Stance',
}
